version: 0.0
os: linux
files:
  - source: /
    destination: /opt/acusense
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
