name: Deploy react-app 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2  # Updated to the latest version
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt  # Path to CA certificates
          # Uncomment the line below for debugging, not for production
          NODE_TLS_REJECT_UNAUTHORIZED: 0  # Disable SSL verification (for testing only)
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MY_AWS_REGION }}  # Using the MY_AWS_REGION secret

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          
          sudo cp -r ./build/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
