name: Deploy react-app 

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-valid-region  # Buraya geçerli bir bölge kodu yazmalısınız.

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          
          sudo cp -r ./build/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
